artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/02839020245c4e199d9ef291b04fd523/artifacts
end_time: 1751394236288
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 02839020245c4e199d9ef291b04fd523
run_name: Default
run_uuid: 02839020245c4e199d9ef291b04fd523
source_name: ''
source_type: 4
source_version: ''
start_time: 1751394236280
status: 3
tags: []
user_id: mle-user
